// Domain types shared across the app.
//
// The dataStore format is inherited from the pre-App-Platform version of
// this tool: each check type ("outliers", "consistency", "completeness")
// is an array of single-key objects mapping a data element (or operand)
// id to the placeholder→value map that was used when generating its
// metadata. Placeholder keys (e.g. "§DE_SOURCE§") are kept verbatim so
// configurations created with the old tool remain readable.

export interface BaseConfig {
    userGroup: string
    dataElementGroup: string
    indicatorGroup: string
    predictorGroup: string
    predictorGroupThreshold: string
    predictorGroupAnalysis: string
    predictorGroupConsistency: string
    // Legacy key (typo) migrated by migrateBaseConfig
    predictorGroupTreshold?: string
}

// Placeholder map: values start as false (meaning "generate a UID") and
// end up as strings after substitution.
export type PlaceholderConfig = Record<string, string | false>

// One entry in a dataStore check array: { [deId]: PlaceholderConfig }
export type StoreEntry = Record<string, PlaceholderConfig>

export type CheckType = 'outliers' | 'consistency' | 'completeness'

export type MetadataKind = 'dataElement' | 'predictor' | 'indicator'

export interface MetadataObject {
    id: string
    name: string
    shortName?: string
    description?: string
    created?: string
    lastUpdated?: string
    numerator?: string
    numeratorDescription?: string
    denominator?: string
    denominatorDescription?: string
    generator?: {
        expression?: string
        description?: string
        displayDescription?: string
        [key: string]: unknown
    }
    sharing?: unknown
    [key: string]: unknown
}

export interface MetadataBundle {
    dataElements?: MetadataObject[]
    predictors?: MetadataObject[]
    indicators?: MetadataObject[]
}

export interface CheckImport {
    metadata: MetadataBundle
    config: PlaceholderConfig
}

// The full set of metadata generated by one Preview action
export interface PendingImport {
    outlier: CheckImport
    consistency: CheckImport
    completeness: CheckImport
    conflicts: Set<string>
}

export interface ImportResultRow {
    label: string
    status: string
    success: boolean
}

export interface NamedRef {
    id: string
    name: string
    shortName: string
}
